### ISSUE TITLE
이벤트 기능 고도화

### ISSUE THREAD

**Issue by Jiwon-Woo** [Together42/nest-backend#15]
### 기능 설명
운영 서버 배포 전 개발 테스트에서 테스트하고 수정합니다.

### ToDo
- [x] 이벤트 삭제 시, casecade로 해당 이벤트에 참석한 참석자들도 삭제
- [x] 이벤트 신청 및 신청 취소는 librarian과 admin 뿐만 아니라 user도 가능하게
- [x] meetups/ranking api를 users/ranking으로 변경
