### ISSUE TITLE
이벤트 기능 고도화

### ISSUE THREAD

**Issue by Jiwon-Woo** [Together42/nest-backend#72]
### 기능 설명
서버 이전 작업 이후 진행할 예정입니다.

### ToDo
- [ ] page, limit 추가
- [ ] 인터셉트를 활용한 로깅 방식
- [ ] 커스텀 필터를 활용한 예외 처리
- [ ] 트랜잭션 처리 및 쿼리빌더가 타입을 any로 반환하는 것 해결하기
- [ ] response body 및 request 값을 제외한 dto 검증
